# Generated by Django 4.1.5 on 2023-06-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0002_expsmoothingforecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpSmoothingParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interp_frequency', models.PositiveIntegerField(verbose_name='Дискрета для интерполяции')),
                ('seasonal_periods', models.PositiveIntegerField(verbose_name='Сезонность ряда')),
                ('forecast_horizon', models.PositiveIntegerField(verbose_name='Горизонт прогноза')),
                ('mae', models.FloatField(verbose_name='MAE')),
                ('rmse', models.FloatField(verbose_name='RMSE')),
                ('mape', models.FloatField(verbose_name='MAPE')),
                ('smape', models.FloatField(verbose_name='SMAPE')),
            ],
        ),
    ]
