# Generated by Django 4.1.5 on 2023-06-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0003_expsmoothingparams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expsmoothingparams',
            name='interp_frequency',
            field=models.CharField(max_length=5, verbose_name='Дискрета для интерполяции'),
        ),
    ]
