# Generated by Django 4.1.5 on 2023-06-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0004_alter_expsmoothingparams_interp_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expsmoothingparams',
            name='mae',
            field=models.FloatField(default=0, verbose_name='MAE'),
        ),
        migrations.AlterField(
            model_name='expsmoothingparams',
            name='mape',
            field=models.FloatField(default=0, verbose_name='MAPE'),
        ),
        migrations.AlterField(
            model_name='expsmoothingparams',
            name='rmse',
            field=models.FloatField(default=0, verbose_name='RMSE'),
        ),
        migrations.AlterField(
            model_name='expsmoothingparams',
            name='smape',
            field=models.FloatField(default=0, verbose_name='SMAPE'),
        ),
    ]
