# Generated by Django 4.1.5 on 2023-06-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0005_alter_expsmoothingparams_mae_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpSmoothingMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mae', models.FloatField(default=0, verbose_name='MAE')),
                ('rmse', models.FloatField(default=0, verbose_name='RMSE')),
                ('mape', models.FloatField(default=0, verbose_name='MAPE')),
                ('smape', models.FloatField(default=0, verbose_name='SMAPE')),
            ],
        ),
        migrations.RemoveField(
            model_name='expsmoothingparams',
            name='mae',
        ),
        migrations.RemoveField(
            model_name='expsmoothingparams',
            name='mape',
        ),
        migrations.RemoveField(
            model_name='expsmoothingparams',
            name='rmse',
        ),
        migrations.RemoveField(
            model_name='expsmoothingparams',
            name='smape',
        ),
    ]
