# Generated by Django 4.1.5 on 2023-06-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('analyst', 'Data analyst'), ('client', 'User')], default='', max_length=10),
        ),
    ]
